# Generated by Django 3.1.7 on 2021-03-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainImages',
            fields=[
                ('imageid', models.CharField(db_column='ImageId', max_length=100)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('imageurl', models.CharField(db_column='imageUrl', max_length=100)),
                ('imagetype', models.CharField(max_length=100)),
                ('postedby', models.CharField(db_column='postedBy', max_length=100)),
                ('restaurantid', models.CharField(db_column='restaurantId', max_length=100)),
                ('userid', models.CharField(db_column='userId', max_length=100)),
            ],
            options={
                'db_table': 'main_images',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
